#!/bin/bash

# Valid Script
ipsaya=$(curl -sS ipv4.icanhazip.com)
data_server=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
date_list=$(date +"%Y-%m-%d" -d "$data_server")

    
# Variables
ip=$(wget -qO- ipv4.icanhazip.com)
srv_date=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
date=$(date +"%Y-%m-%d" -d "$srv_date")
ip_url="https://ip.yha.my.id/ip"
city=$(cat /etc/xray/city 2>/dev/null || echo "Unknown city")
pubkey=$(cat /etc/slowdns/server.pub 2>/dev/null || echo "Pubkey not available")
domain=$(cat /etc/xray/domain 2>/dev/null || hostname -f)
# uuid=$(cat /proc/sys/kernel/random/uuid)

echo -e "————————————————————————————————————————————————————"
echo -e "             Add Xray Vless Account"
echo -e "————————————————————————————————————————————————————"

while true; do
    read -p "   Name: " user
    if [[ ${#user} -lt 3 || ! "$user" =~ ^[a-zA-Z0-9_-]+$ ]]; then
        printf "\033[1A\033[0J"
        echo -e "${red}   Username cannot be empty${reset}"
        continue
    fi
    if grep -q "^### $user " /etc/xray/vless/config.json; then
        random_number=$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c 5)
        user="${random_number}${user}"
        echo -e "${yellow}   Username already exists. New username used: $user${reset}"
        break
    else
        break
    fi
done



read -p "Password: " uuid
until [[ $duration =~ ^[0-9]+$ ]]; do
    read -p "   Active period (days): " duration
    if [[ -z "$duration" ]]; then
        echo -e "${red}Active period cannot be empty. Please try again.${reset}"
    fi
done
until [[ $quota =~ ^[0-9]+$ ]]; do
    read -p "   User Quota (GB): " quota
    if [[ -z "$quota" ]]; then
        echo -e "${red}Quota limit cannot be empty. Please try again.${reset}"
    fi
done
until [[ $ip_limit =~ ^[0-9]+$ ]]; do
    read -p "   User Limit (IP): " ip_limit
    if [[ -z "$ip_limit" ]]; then
        echo -e "${red}IP limit cannot be empty. Please try again.${reset}"
    fi
done

# Account creation process
exp=$(date -d "$duration days" +"%Y-%m-%d")
if [ ! -f "/etc/xray/vless/config.json" ]; then
    echo -e "${red}Vless configuration file not found. Creating new file...${reset}"
    mkdir -p /etc/xray/vless
    echo '{"inbounds": []}' >/etc/xray/vless/config.json
fi
sed -i '/#vless$/a\### '"$user $exp"'\
},{"id": "'""$uuid""'","email": "'""$user""'"' /etc/xray/vless/config.json
sed -i '/#vlessgrpc$/a\### '"$user $exp"'\
},{"id": "'""$uuid""'","email": "'""$user""'"' /etc/xray/vless/config.json

# Create configuration files
cat >/etc/xray/vless/$user-tls.json <<EOF
{
    "v": "2",
    "ps": "$user WS (CDN) TLS",
    "add": "${domain}",
    "port": "443",
    "id": "${uuid}",
    "aid": "0",
    "net": "ws",
    "path": "/whatever/vless",
    "type": "none",
    "host": "${domain}",
    "tls": "tls"
}
EOF

cat >/etc/xray/vless/$user-non.json <<EOF
{
    "v": "2",
    "ps": "$user WS (CDN) NTLS",
    "add": "${domain}",
    "port": "80",
    "id": "${uuid}",
    "aid": "0",
    "net": "ws",
    "path": "/whatever/vless",
    "type": "none",
    "host": "${domain}",
    "tls": "none"
}
EOF

cat >/etc/xray/vless/$user-grpc.json <<EOF
{
    "v": "2",
    "ps": "$user (SNI) GRPC",
    "add": "${domain}",
    "port": "443",
    "id": "${uuid}",
    "aid": "0",
    "net": "grpc",
    "path": "vless-grpc",
    "type": "none",
    "host": "${domain}",
    "tls": "tls"
}
EOF

# Create configuration file for OpenClash
cat >/var/www/html/vless-$user.txt <<-END
---------------------
# Vless WS (CDN) Format
---------------------

- name: Vless-$user-WS (CDN)
  type: vless
  server: ${domain}
  port: 443
  uuid: ${uuid}
  cipher: auto
  udp: true
  tls: true
  skip-cert-verify: true
  servername: ${domain}
  network: ws
  ws-opts:
    path: /whatever/vless
    headers:
      Host: ${domain}
---------------------
# Vless WS (CDN) Non TLS Format
---------------------

- name: Vless-$user-WS (CDN) Non TLS
  type: vless
  server: ${domain}
  port: 80
  uuid: ${uuid}
  cipher: auto
  udp: true
  tls: false
  skip-cert-verify: false
  servername: ${domain}
  network: ws
  ws-opts:
    path: /whatever/vless
    headers:
      Host: ${domain}
---------------------
# Vless gRPC (SNI) Format
---------------------

- name: Vless-$user-gRPC (SNI)
  server: ${domain}
  port: 443
  type: vless
  uuid: ${uuid}
  cipher: auto
  network: grpc
  tls: true
  servername: ${domain}
  skip-cert-verify: true
  grpc-opts:
    grpc-service-name: vless-grpc

---------------------
# Vless Account Links
---------------------
TLS Link : vless://${uuid}@${domain}:443?path=/whatever/vless&security=tls&encryption=none&host=${domain}&type=ws#${user}-WS-TLS
---------------------
Non-TLS Link : vless://${uuid}@${domain}:80?path=/whatever/vless&encryption=none&host=${domain}&type=ws#${user}-WS-NTLS
---------------------
GRPC Link : vless://${uuid}@${domain}:443?mode=gun&security=tls&encryption=none&type=grpc&serviceName=vless-grpc&sni=${domain}#${user}-gRPC
---------------------

END

# Generate Vless links
vless_tls="vless://${uuid}@${domain}:443?path=/whatever/vless&security=tls&encryption=none&host=${domain}&type=ws#${user}-WS-TLS"
vless_non="vless://${uuid}@${domain}:80?path=/whatever/vless&encryption=none&host=${domain}&type=ws#${user}-WS-NTLS"
vless_grpc="vless://${uuid}@${domain}:443?mode=gun&security=tls&encryption=none&type=grpc&serviceName=vless-grpc&sni=${domain}#${user}-gRPC"

# Restart services
if ! systemctl restart vless@config >/dev/null 2>&1; then
    echo -e "${red}Failed to restart vless service. Please check system logs for more information.${reset}"
    exit 1
fi

# Exception if configuration file doesn't exist
if [ ! -f "/etc/xray/vless/config.json" ]; then
    echo "Warning: Vless configuration file not found. Creating new file..."
    mkdir -p /etc/xray/vless
    echo '{"inbounds": []}' >/etc/xray/vless/config.json
    systemctl restart vless@config
fi

# Create directory if it doesn't exist
if [ ! -d "/etc/xray/vless" ]; then
    echo "Directory /etc/xray/vless not found. Creating directory..."
    mkdir -p /etc/xray/vless
    if [ $? -ne 0 ]; then
        echo "Failed to create directory /etc/xray/vless. Make sure you have sufficient permissions."
        exit 1
    fi
fi

# Set default values if empty
[ -z ${ip_limit} ] && ip_limit="0"
[ -z ${quota} ] && quota="0"

# Convert Quota to bytes
quota_bytes=$((${quota} * 1024 * 1024 * 1024))

# Save quota and IP limit data
if [[ ${quota} != "0" ]]; then
    echo "${quota_bytes}" >/etc/xray/vless/${user}
    echo "${ip_limit}" >/etc/xray/vless/${user}IP
fi

# Update database
db_file="/etc/xray/vless/.vless.db"
temp_file="/etc/xray/vless/.vless.db.tmp"

# Remove old entry if exists
if [ -f "$db_file" ]; then
    grep -v "^### ${user} " "$db_file" >"$temp_file"
    mv "$temp_file" "$db_file"
else
    touch "$db_file"
fi

# Add new entry
echo "### ${user} ${exp} ${uuid}" >>"$db_file"



# Save log
{
    echo "───────────────────────────"
    echo "    xray/vless account    "
    echo "───────────────────────────"
    echo "description  : ${user}"
    echo "host server  : ${domain}"    
    echo "location     : $city"
    echo "port tls     : 443"
    echo "port non tls : 80, 8080"
    echo "port dns     : 443, 53"
    echo "port grpc    : 443"
    echo "security     : auto"
    echo "network      : ws or grpc"
    echo "path         : /whatever/vless"
    echo "servicename  : vless-grpc"
    echo "user id      : ${uuid}"
    echo "public key   : ${pubkey}"
    echo "───────────────────────────"
    echo "tls link     : ${vless_tls}"
    echo "───────────────────────────"
    echo "ntls link    : ${vless_non}"
    echo "───────────────────────────"
    echo "grpc link    : ${vless_grpc}"
    echo "───────────────────────────"
    echo "openclash format : https://${domain}:81/vless-$user.txt"
    echo "───────────────────────────"
    echo "expires on   : $exp"
    echo ""
} >> /etc/xray/vless/log-create-${user}.log

clear
# Display account information
clear 
echo -e "—————————————————————————————————————"
echo -e  "    Xray/vless Account    "
echo -e "—————————————————————————————————————"
echo -e "Description  : ${user}"
echo -e "Host Server  : ${domain}"
echo -e "Location     : $city"
echo -e "Port TLS     : 443"
echo -e "Port non TLS : 80, 8080"
echo -e "Port DNS     : 443, 53"
echo -e "Port GRPC    : 443"
echo -e "Security     : auto"
echo -e "Network      : WS or gRPC"
echo -e "Path         : /whatever/vless "
echo -e "ServiceName  : vless-grpc"
echo -e "User ID      : ${uuid}"
echo -e "Public Key   : ${pubkey}"
echo -e "—————————————————————————————————————"
echo -e "TLS Link    : ${vless_tls}"
echo -e "—————————————————————————————————————"
echo -e "NTLS Link   : ${vless_non}"
echo -e "—————————————————————————————————————"
echo -e "GRPC Link   : ${vless_grpc}"
echo -e "—————————————————————————————————————"
echo -e "OpenClash Format : https://${domain}:81/vless-$user.txt"
echo -e "—————————————————————————————————————"
echo -e "Expires On  : $exp"

