#!/bin/bash

# Valid Script
ipsaya=$(curl -sS ipv4.icanhazip.com)
data_server=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
date_list=$(date +"%Y-%m-%d" -d "$data_server")


# Variables
ip=$(wget -qO- ipv4.icanhazip.com)
srv_date=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
date=$(date +"%Y-%m-%d" -d "$srv_date")
city=$(cat /etc/xray/city 2>/dev/null || echo "Unknown city")
pubkey=$(cat /etc/slowdns/server.pub 2>/dev/null || echo "Pubkey not available")
ns_domain=$(cat /etc/xray/dns 2>/dev/null || echo "NS domain not set")
domain=$(cat /etc/xray/domain 2>/dev/null || hostname -f)
uuid=$(cat /proc/sys/kernel/random/uuid)


clear

# User data input
echo "┌─────────────────────────────────────────┐"
echo "│        Script by XTRIMER-TUNNEL         │"
echo "│     Input xray/trojan account deps      │"
echo "│            Enter User Data              │"
echo "└─────────────────────────────────────────┘"

# Generate random username
# user=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 8 | head -n 1)

# echo "   Username : $user"

while true; do
    read -p "   Name: " user
    if [[ ${#user} -lt 3 || ! "$user" =~ ^[a-zA-Z0-9_-]+$ ]]; then
        printf "\033[1A\033[0J"
        echo -e "${red}   Username cannot be empty${reset}"
        continue
    fi
    if grep -q "^### $user " /etc/xray/trojan/config.json; then
        random_number=$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c 5)
        user="${random_number}${user}"
        echo -e "${yellow}   Username already exists. New username used: $user${reset}"
        break
    else
        break
    fi
done


until [[ $duration =~ ^[0-9]+$ ]]; do
    read -p "   Active period (minutes): " duration
    if [[ -z "$duration" ]]; then
        echo -e "${red}   Active period cannot be empty${reset}"
    fi
done

# Account creation process
exp=$(date -d "+$duration minutes" +"%Y-%m-%d %H:%M:%S")
if [ ! -f "/etc/xray/trojan/config.json" ]; then
    echo "Configuration file not found. Creating new file..."
    echo '{"inbounds": []}' > /etc/xray/trojan/config.json
fi

sed -i '/#trojan$/a\### '"$user $exp"'\
},{"password": "'""$uuid""'","email": "'""$user""'"' /etc/xray/trojan/config.json
sed -i '/#trojangrpc$/a\### '"$user $exp"'\
},{"password": "'""$uuid""'","email": "'""$user""'"' /etc/xray/trojan/config.json

# Create configuration files
cat >/etc/xray/$user-tls.json <<EOF
{
    "v": "2",
    "ps": "$user WS (CDN) TLS",
    "add": "${domain}",
    "port": "443",
    "id": "${uuid}",
    "aid": "0",
    "net": "ws",
    "path": "/trojan-ws",
    "type": "none",
    "host": "${domain}",
    "tls": "tls"
}
EOF

cat >/etc/xray/$user-grpc.json <<EOF
{
    "v": "2",
    "ps": "$user (SNI) GRPC",
    "add": "${domain}",
    "port": "443",
    "id": "${uuid}",
    "aid": "0",
    "net": "grpc",
    "path": "trojan-grpc",
    "type": "none",
    "host": "${domain}",
    "tls": "tls"
}
EOF

tmux new-session -d -s "trial_trojan_$user" "trial trialtr $user $duration"
# Generate Trojan links
trojan_tls="trojan://${uuid}@${domain}:443?path=/trojan-ws&security=tls&host=${domain}&type=ws&sni=${domain}#${user}-WS-TLS"
trojan_grpc="trojan://${uuid}@${domain}:443?mode=gun&security=tls&type=grpc&serviceName=trojan-grpc&sni=${domain}#${user}-gRPC"

# Restart service
if ! systemctl restart trojan@config > /dev/null 2>&1; then
    echo -e "${red}Failed to restart trojan service. Please check system logs for more information.${reset}"
    exit 1
fi

# Display account information
clear
clear
echo -e "—————————————————————————————————————"
echo -e "    Xray/Trojan Account    "
echo -e "—————————————————————————————————————"
echo -e "Description  : ${user}"
echo -e "Host Server  : ${domain}"
echo -e "Location     : ${city}"
echo -e "TLS Port     : 443"
echo -e "DNS Port     : 443, 53"
echo -e "GRPC Port    : 443"
echo -e "Security     : auto"
echo -e "Network      : WS or gRPC"
echo -e "Path         : /whatever/trojan-ws"
echo -e "ServiceName  : trojan-grpc"
echo -e "Password     : ${uuid}"
echo -e "Public Key   : ${pubkey}"
echo -e "───────────────────────────"
echo -e "TLS Link     : ${trojan_tls}"
echo -e "—————————————————————————————————————"
echo -e "GRPC Link    : ${trojan_grpc}"
echo -e "—————————————————————————————————————"
echo -e "OpenClash Format : https://${domain}:81/trojan-${user}.txt"
echo -e "—————————————————————————————————————"
echo -e "Expires On   : ${duration} minutes"

